files:
  client.mustache:
    templateType: SupportingFiles
    folder: lakefs_sdk_async
    destinationFilename: client.py

  requirements.mustache:
    templateType: SupportingFiles
    destinationFilename: requirements.txt
library: asyncio

